name: snackify
description: A customizable and fancy SnackBar widget for Flutter with advanced customization options, such as background color, text style, icon support, margin, and more.
version: 1.1.0
license: MIT
homepage: https://github.com/Atanu-Sabyasachi/snackify/tree/master
repository: https://github.com/Atanu-Sabyasachi/snackify/tree/master

environment:
  sdk: ^3.5.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/snack_images/
