name: snackify
description: Snackify is a Flutter package for creating animated, customizable snackbars with options for message type, position, duration, and more, improving user notifications.
version: 1.2.3
license: MIT
homepage: https://github.com/Atanu-Sabyasachi/snackify/tree/master
repository: https://github.com/Atanu-Sabyasachi/snackify/tree/master
funding:
  - https://buymeacoffee.com/atanusabyasachi

environment:
  sdk: ^3.5.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  flutter_tts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/snack_images/
